# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ci:
    autofix_commit_msg: |
      [pre-commit.ci] auto code formatting
    autofix_prs: false
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    submodules: false

# Please update the rev: SHAs below with this command:
# pre-commit autoupdate --freeze
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: local
    hooks:
      - id: check-spdx
        name: Check SPDX Headers
        entry: python ./toolshed/check_spdx.py
        language: python
        additional_dependencies:
          - https://files.pythonhosted.org/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl
        args: ["--fix"]

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    # TODO: re-enable after fixing inherited numba docstring patterns
    # - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: trailing-whitespace
      exclude: '.+\.patch'

default_language_version:
      python: python3
