# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_call:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0  # v0.9.5
        with:
          pixi-version: "v0.63.2"
          environments: docs
          cache: false
          locked: false
      - name: Docs build
        run: pixi run -e docs build-docs
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload docs
        if: "!cancelled()"
        uses: actions/upload-artifact@v7.0.1
        with:
          name: docs
          path: ${{ github.workspace }}/docs/build/html
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/build/html
